import Head from "next/head";
import { FC } from "react";
import Footer from "./footer";
import Header from "./header";


const Layout: FC = ({ children }) => {
    return (
        <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header/>
        <main>
            {children}
        </main>
        <Footer/>
        </>
    );
}

export default Layout;